// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'usernotice.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserNotice _$UserNoticeFromJson(Map<String, dynamic> json) => UserNotice(
      json['uid'] as int,
      json['unreadComment'] as int,
      json['readCommentindex'] as int,
      json['unreadReply'] as int,
      json['readReplyindex'] as int,
      json['unreadSysnotice'] as int,
      json['readSysnoticeindex'] as int,
      json['unreadMember'] as int,
      json['readMember'] as int,
      json['unreadFollow'] as int,
      json['readFollow'] as int,
      json['unevaluateActivity'] as int,
      json['evaluateActivity'] as int,
      json['unreadEvaluate'] as int,
      json['readEvaluate'] as int,
      json['unreadEvaluatereply'] as int,
      json['readEvaluatereply'] as int,
      json['unreadFriend'] as int,
      json['readFriend'] as int,
      json['isUserUpdate'] as int,
      json['unreadShared'] as int,
      json['readShared'] as int,
      json['unreadOrderpending'] as int,
      json['unreadOrderfinish'] as int,
      json['unreadActlike'] as int,
      json['readActlike'] as int,
      json['unreadCommentlike'] as int,
      json['readCommentlike'] as int,
      json['unreadEvaluatelike'] as int,
      json['readEvaluatelike'] as int,
      json['unreadBuglike'] as int,
      json['readBuglike'] as int,
      json['unreadSuggestlike'] as int,
      json['readSuggestlike'] as int,
      json['unreadBugcomment'] as int,
      json['readBugcomment'] as int,
      json['unreadSuggestcomment'] as int,
      json['readSuggestcomment'] as int,
      json['unreadBugreply'] as int,
      json['readBugreply'] as int,
      json['unreadSuggestreply'] as int,
      json['readSuggestreply'] as int,
      json['unreadBugcommentlike'] as int,
      json['readBugcommentlike'] as int,
      json['unreadSuggestcommentlike'] as int,
      json['readSuggestcommentlike'] as int,
      json['unreadGpmsg'] as int,
      json['readGpmsg'] as int,
      json['unreadCommunitymsg'] as int,
      json['readCommunitymsg'] as int,
      json['unreadSinglemsg'] as int,
      json['readSinglemsg'] as int,
      json['unreadGoodpricecomment'] as int,
      json['readGoodpricecommentindex'] as int,
      json['unreadGoodpricereply'] as int,
      json['readGoodpricereplyindex'] as int,
      json['unreadGoodpricecommentlike'] as int,
      json['readGoodpricecommentlike'] as int,
      json['orderExpiration'] as int,
      json['unreadMomentlike'] as int,
      json['readMomentlike'] as int,
      json['unreadMomentcomment'] as int,
      json['readMomentcomment'] as int,
      json['unreadMomentreply'] as int,
      json['readMementreply'] as int,
      json['unreadMomentcommentlike'] as int,
      json['readMomentcommentlike'] as int,
    );

Map<String, dynamic> _$UserNoticeToJson(UserNotice instance) =>
    <String, dynamic>{
      'uid': instance.uid,
      'unreadComment': instance.unreadComment,
      'readCommentindex': instance.readCommentindex,
      'unreadReply': instance.unreadReply,
      'readReplyindex': instance.readReplyindex,
      'unreadSysnotice': instance.unreadSysnotice,
      'readSysnoticeindex': instance.readSysnoticeindex,
      'unreadMember': instance.unreadMember,
      'readMember': instance.readMember,
      'unreadFollow': instance.unreadFollow,
      'readFollow': instance.readFollow,
      'unevaluateActivity': instance.unevaluateActivity,
      'evaluateActivity': instance.evaluateActivity,
      'unreadEvaluate': instance.unreadEvaluate,
      'readEvaluate': instance.readEvaluate,
      'unreadEvaluatereply': instance.unreadEvaluatereply,
      'readEvaluatereply': instance.readEvaluatereply,
      'unreadFriend': instance.unreadFriend,
      'readFriend': instance.readFriend,
      'isUserUpdate': instance.isUserUpdate,
      'unreadShared': instance.unreadShared,
      'readShared': instance.readShared,
      'unreadOrderpending': instance.unreadOrderpending,
      'unreadOrderfinish': instance.unreadOrderfinish,
      'unreadActlike': instance.unreadActlike,
      'readActlike': instance.readActlike,
      'unreadCommentlike': instance.unreadCommentlike,
      'readCommentlike': instance.readCommentlike,
      'unreadEvaluatelike': instance.unreadEvaluatelike,
      'readEvaluatelike': instance.readEvaluatelike,
      'unreadBuglike': instance.unreadBuglike,
      'readBuglike': instance.readBuglike,
      'unreadSuggestlike': instance.unreadSuggestlike,
      'readSuggestlike': instance.readSuggestlike,
      'unreadMomentlike': instance.unreadMomentlike,
      'readMomentlike': instance.readMomentlike,
      'unreadBugcomment': instance.unreadBugcomment,
      'readBugcomment': instance.readBugcomment,
      'unreadSuggestcomment': instance.unreadSuggestcomment,
      'readSuggestcomment': instance.readSuggestcomment,
      'unreadMomentcomment': instance.unreadMomentcomment,
      'readMomentcomment': instance.readMomentcomment,
      'unreadBugreply': instance.unreadBugreply,
      'readBugreply': instance.readBugreply,
      'unreadSuggestreply': instance.unreadSuggestreply,
      'readSuggestreply': instance.readSuggestreply,
      'unreadMomentreply': instance.unreadMomentreply,
      'readMementreply': instance.readMementreply,
      'unreadGoodpricecomment': instance.unreadGoodpricecomment,
      'readGoodpricecommentindex': instance.readGoodpricecommentindex,
      'unreadGoodpricereply': instance.unreadGoodpricereply,
      'readGoodpricereplyindex': instance.readGoodpricereplyindex,
      'unreadBugcommentlike': instance.unreadBugcommentlike,
      'readBugcommentlike': instance.readBugcommentlike,
      'unreadSuggestcommentlike': instance.unreadSuggestcommentlike,
      'readSuggestcommentlike': instance.readSuggestcommentlike,
      'unreadMomentcommentlike': instance.unreadMomentcommentlike,
      'readMomentcommentlike': instance.readMomentcommentlike,
      'unreadGoodpricecommentlike': instance.unreadGoodpricecommentlike,
      'readGoodpricecommentlike': instance.readGoodpricecommentlike,
      'unreadGpmsg': instance.unreadGpmsg,
      'readGpmsg': instance.readGpmsg,
      'unreadCommunitymsg': instance.unreadCommunitymsg,
      'readCommunitymsg': instance.readCommunitymsg,
      'unreadSinglemsg': instance.unreadSinglemsg,
      'readSinglemsg': instance.readSinglemsg,
      'orderExpiration': instance.orderExpiration,
    };
